package Proyecto;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author COCO
 */
public class FrmVistaPedidoCatalogo extends javax.swing.JFrame {

    /**
     * Creates new form FrmVistaPedidoCatalogo
     */
    public FrmVistaPedidoCatalogo() {
        initComponents();
          this.setLocationRelativeTo(null);
        cargarNombrePedido();
        cargarCodigoPedido();
        cargar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabla1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboNombre = new javax.swing.JComboBox<>();
        btnNombrePedido = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cboCodigo = new javax.swing.JComboBox<>();
        btnCodigoPedido = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        tblTabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTabla1);

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MANUALIDADES ANAFER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("CONSULTAR");

        jLabel4.setText("POR NOMBRE DE PEDIDO");

        btnNombrePedido.setText("CONSULTAR");
        btnNombrePedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNombrePedidoActionPerformed(evt);
            }
        });

        jLabel5.setText("POR CODIGO DE PEDIDO");

        btnCodigoPedido.setText("CONSULTAR");
        btnCodigoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodigoPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboNombre, 0, 172, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboCodigo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNombrePedido, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCodigoPedido, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNombrePedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCodigoPedido)
                .addGap(30, 30, 30))
        );

        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CARGAR TODO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("MATERIALES NECESARIOS PARA PEDIDO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(27, 27, 27))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargar()
    {
            String usuario="system";
    String password="oracle";
    String ssid="bbdd01";
    String host="localhost";
        int puerto=1521;
        String cadenaConexion;
        cadenaConexion="jdbc:oracle:thin:@"+host+":"+puerto+":"+ssid;
        String sentenciaSQL="select distinct pedido_catalogo.cod_ped AS CODIGO_PEDIDO,nom_ped AS NOMBRE_PEDIDO,pedido_catalogo.cod_cat AS CODIGO_MATERIAL,nom_cat AS NOMBRE_MATERIAL from pedido_catalogo  join pedido  on(pedido_catalogo.COD_PED=pedido.cod_ped) join catalogo on(pedido_catalogo.cod_cat=catalogo.cod_cat)";
        
        try(
               Connection miConexion=DriverManager.getConnection(cadenaConexion,usuario,password);
                Statement miSentencia=miConexion.createStatement();
                ResultSet miResultSet=miSentencia.executeQuery(sentenciaSQL);
                )
        {
            Vector miListaDeCampos=new Vector();
            int numeroDeCampos;
            ResultSetMetaData miMetaData;
            miMetaData=miResultSet.getMetaData();
            numeroDeCampos=miMetaData.getColumnCount();
            
            for(int i=0;i<miMetaData.getColumnCount();i++){
               miListaDeCampos.add(miMetaData.getColumnName(i+1));
            }
            DefaultTableModel miDefaultTableModel=new DefaultTableModel(miListaDeCampos,0);
            int cont=0;
            while(miResultSet.next())
            {
                cont++;
                Object[] miRenglon=new Object[numeroDeCampos];
                for(int i=0;i<numeroDeCampos;i++)
                {
                miRenglon[i]=miResultSet.getObject(i+1);    
                }
                miDefaultTableModel.addRow(miRenglon);
            }
            tblTabla1.setModel(miDefaultTableModel);
        }
        catch(SQLException e)
        {
              JOptionPane.showMessageDialog(null, "Error encontrado : "+e.getMessage());   
        }
    }
    private void btnNombrePedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNombrePedidoActionPerformed
           String usuario="system";
    String password="oracle";
    String ssid="bbdd01";
    String host="localhost";
        int puerto=1521;
        String cadenaConexion;
        cadenaConexion="jdbc:oracle:thin:@"+host+":"+puerto+":"+ssid;
        String sentenciaSQL="select distinct pedido_catalogo.cod_ped AS CODIGO_PEDIDO,nom_ped AS NOMBRE_PEDIDO,pedido_catalogo.cod_cat AS CODIGO_MATERIAL,nom_cat  AS NOMBRE_MATERIAL from pedido_catalogo  join pedido  on(pedido_catalogo.COD_PED=pedido.cod_ped) join catalogo on(pedido_catalogo.cod_cat=catalogo.cod_cat) where nom_ped='"+cboNombre.getSelectedItem()+"'";

        try(
            Connection miConexion=DriverManager.getConnection(cadenaConexion,usuario,password);
            Statement miSentencia=miConexion.createStatement();
            ResultSet miResultSet=miSentencia.executeQuery(sentenciaSQL);
        )
        {
            Vector miListaDeCampos=new Vector();
            int numeroDeCampos;
            ResultSetMetaData miMetaData;
            miMetaData=miResultSet.getMetaData();
            numeroDeCampos=miMetaData.getColumnCount();

            for(int i=0;i<miMetaData.getColumnCount();i++){
                miListaDeCampos.add(miMetaData.getColumnName(i+1));
            }
            DefaultTableModel miDefaultTableModel=new DefaultTableModel(miListaDeCampos,0);
            int cont=0;
            while(miResultSet.next())
            {
                cont++;
                Object[] miRenglon=new Object[numeroDeCampos];
                for(int i=0;i<numeroDeCampos;i++)
                {
                    miRenglon[i]=miResultSet.getObject(i+1);
                }
                miDefaultTableModel.addRow(miRenglon);
            }
            tblTabla1.setModel(miDefaultTableModel);
        }
        catch(SQLException e)
        {
              JOptionPane.showMessageDialog(null, "Error encontrado : "+e.getMessage());
        }
    }//GEN-LAST:event_btnNombrePedidoActionPerformed

     private void cargarNombrePedido()
    {
            String usuario="system";
    String password="oracle";
    String ssid="bbdd01";
    String host="localhost";
        int puerto=1521;
        String cadenaConexion;
        cadenaConexion="jdbc:oracle:thin:@"+host+":"+puerto+":"+ssid;
        String sentenciaSQL="select distinct nom_ped from pedido";
        
        try(
               Connection miConexion=DriverManager.getConnection(cadenaConexion,usuario,password);
                Statement miSentencia=miConexion.createStatement();
                ResultSet miResultSet=miSentencia.executeQuery(sentenciaSQL);
                )
        {
                      while(miResultSet.next()){
                cboNombre.addItem(miResultSet.getString("nom_ped"));
            }
        }
        catch(SQLException e)
        {
              JOptionPane.showMessageDialog(null, "Error encontrado : "+e.getMessage());  
        }
    }
      private void cargarCodigoPedido()
    {
           String usuario="system";
    String password="oracle";
    String ssid="bbdd01";
    String host="localhost";
        int puerto=1521;
        String cadenaConexion;
        cadenaConexion="jdbc:oracle:thin:@"+host+":"+puerto+":"+ssid;
        String sentenciaSQL="select distinct cod_ped from pedido";
        
        try(
               Connection miConexion=DriverManager.getConnection(cadenaConexion,usuario,password);
                Statement miSentencia=miConexion.createStatement();
                ResultSet miResultSet=miSentencia.executeQuery(sentenciaSQL);
                )
        {
                      while(miResultSet.next()){
                cboCodigo.addItem(miResultSet.getString("cod_ped"));
            }
        }
        catch(SQLException e)
        {
              JOptionPane.showMessageDialog(null, "Error encontrado : "+e.getMessage());   
        }
    }
    private void btnCodigoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodigoPedidoActionPerformed
           String usuario="system";
    String password="oracle";
    String ssid="bbdd01";
    String host="localhost";
        int puerto=1521;
        String cadenaConexion;
        cadenaConexion="jdbc:oracle:thin:@"+host+":"+puerto+":"+ssid;
        String sentenciaSQL="select distinct pedido_catalogo.cod_ped AS CODIGO_PEDIDO,nom_ped AS NOMBRE_PEDIDO,pedido_catalogo.cod_cat AS CODIGO_MATERIAL,nom_cat AS NOMBRE_MATERIAL from pedido_catalogo  join pedido  on(pedido_catalogo.COD_PED=pedido.cod_ped) join catalogo on(pedido_catalogo.cod_cat=catalogo.cod_cat) where pedido.cod_ped='"+cboCodigo.getSelectedItem()+"'";

        try(
            Connection miConexion=DriverManager.getConnection(cadenaConexion,usuario,password);
            Statement miSentencia=miConexion.createStatement();
            ResultSet miResultSet=miSentencia.executeQuery(sentenciaSQL);
        )
        {
            Vector miListaDeCampos=new Vector();
            int numeroDeCampos;
            ResultSetMetaData miMetaData;
            miMetaData=miResultSet.getMetaData();
            numeroDeCampos=miMetaData.getColumnCount();

            for(int i=0;i<miMetaData.getColumnCount();i++){
                miListaDeCampos.add(miMetaData.getColumnName(i+1));
            }
            DefaultTableModel miDefaultTableModel=new DefaultTableModel(miListaDeCampos,0);
            int cont=0;
            while(miResultSet.next())
            {
                cont++;
                Object[] miRenglon=new Object[numeroDeCampos];
                for(int i=0;i<numeroDeCampos;i++)
                {
                    miRenglon[i]=miResultSet.getObject(i+1);
                }
                miDefaultTableModel.addRow(miRenglon);
            }
            tblTabla1.setModel(miDefaultTableModel);
        }
        catch(SQLException e)
        {
              JOptionPane.showMessageDialog(null, "Error encontrado : "+e.getMessage());
        }
    }//GEN-LAST:event_btnCodigoPedidoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
cargar();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVistaPedidoCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVistaPedidoCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVistaPedidoCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVistaPedidoCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVistaPedidoCatalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCodigoPedido;
    private javax.swing.JButton btnNombrePedido;
    private javax.swing.JComboBox<String> cboCodigo;
    private javax.swing.JComboBox<String> cboNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTabla1;
    // End of variables declaration//GEN-END:variables
}
